CIFAR10:
    ResNet18:
        BadNets:
            exp_1: "2025-06-05_12:13:46" # random_seed: 1
            exp_2: "2025-06-09_16:04:11" 
            exp_3: "2025-06-10_19:49:02"
            exp_4: "2025-06-08_21:52:02"
            exp_5: "2025-06-10_19:52:30"
            exp_6: "2025-06-10_19:53:31" # 210
            exp_7: "2025-06-08_21:52:25"
            exp_8: "2025-06-10_19:53:58" # 210
            exp_9: "2025-06-10_19:54:09" # 210
            exp_10: "2025-06-08_21:53:12"
        IAD:
            exp_1: "2025-06-05_18:21:24"
            exp_2: "2025-06-13_22:28:18" # 210
            exp_3: "2025-06-18_12:44:38" # 210
            exp_4: "2025-06-09_02:46:56"
            exp_5: "2025-06-13_22:29:00" # 210
            exp_6: "2025-06-13_22:29:09" # 210
            exp_7: "2025-06-09_04:10:33"
            exp_8: "2025-06-13_22:30:57" # 210
            exp_9: "2025-06-13_22:31:05" # 210
            exp_10: "2025-06-09_04:17:36"
        Refool:
            exp_1: "2025-06-06_06:32:25"
            exp_2: "2025-06-14_05:33:19" # 210
            exp_3: "2025-06-13_22:28:05" # 210
            exp_4: "2025-06-09_08:05:40"
            exp_5: "2025-06-14_04:45:58" # 210
            exp_6: "2025-06-14_04:46:18" # 210
            exp_7: "2025-06-09_09:51:42"
            exp_8: "2025-06-14_04:49:37" # 210
            exp_9: "2025-06-14_04:49:25" # 210
            exp_10: "2025-06-09_09:53:14"
        WaNet:
            exp_1: "2025-06-18_12:45:00" # 210
            exp_2: "2025-06-15_11:29:58" # 210
            exp_3: "2025-06-15_04:34:01" # 210
            exp_4: "2025-06-09_15:06:46"
            exp_5: "2025-06-15_11:37:37" # 210
            exp_6: "2025-06-15_11:13:15" # 210
            exp_7: "2025-06-15_03:48:01" # 210
            exp_8: "2025-06-15_09:56:04" # 210
            exp_9: "2025-06-15_10:57:10" # 210
            exp_10: "2025-06-15_03:48:01" # 210
    VGG19:
        BadNets:
            exp_1: "2025-06-10_19:56:49" # 210
            exp_2: "2025-06-10_19:57:15" # 210
            exp_3: "2025-06-10_19:57:20" # 210
            exp_4: "2025-06-10_19:57:32" # 210
            exp_5: "2025-06-10_19:57:37" # 210
            exp_6: "2025-06-10_19:57:46" # 210
            exp_7: "2025-06-10_19:57:51" # 210
            exp_8: "2025-06-10_19:58:01" # 210
            exp_9: "2025-06-10_19:58:07" # 210
            exp_10: "2025-06-10_19:59:13" # 210
        IAD:
            exp_1: "2025-06-13_22:33:47" # 210
            exp_2: "2025-06-13_22:33:50" # 210
            exp_3: "2025-06-13_22:33:48" # 210
            exp_4: "2025-06-13_22:33:51" # 210
            exp_5: "2025-06-13_22:33:59" # 210
            exp_6: "2025-06-13_22:34:10" # 210
            exp_7: "2025-06-13_22:35:00" # 210
            exp_8: "2025-06-13_22:50:35" # 210
            exp_9: "2025-06-13_22:50:52" # 210
            exp_10: "2025-06-13_22:51:06" # 210
        Refool:
            exp_1: "2025-06-14_04:18:11" # 210
            exp_2: "2025-06-14_04:17:18" # 210
            exp_3: "2025-06-14_05:02:19" # 210
            exp_4: "2025-06-14_05:01:50" # 210
            exp_5: "2025-06-14_04:44:03" # 210
            exp_6: "2025-06-14_04:49:18" # 210
            exp_7: "2025-06-14_03:28:53" # 210
            exp_8: "2025-06-14_03:54:29" # 210
            exp_9: "2025-06-14_05:16:55" # 210
            exp_10: "2025-06-14_05:36:54" # 210
        WaNet:
            exp_1: "2025-06-15_10:30:00" # 210
            exp_2: "2025-06-15_11:07:27" # 210
            exp_3: "2025-06-15_11:38:17" # 210
            exp_4: "2025-06-15_11:13:20" # 210
            exp_5: "2025-06-15_10:46:28" # 210
            exp_6: "2025-06-15_11:17:18" # 210
            exp_7: "2025-06-15_10:06:05" # 210
            exp_8: "2025-06-15_09:46:13" # 210
            exp_9: "2025-06-15_11:21:07" # 210
            exp_10: "2025-06-15_11:50:31" # 210
    DenseNet:
        BadNets:
            exp_1: "2025-06-10_20:00:36" # 210
            exp_2: "2025-06-10_20:00:45" # 210
            exp_3: "2025-06-10_20:00:52" # 210
            exp_4: "2025-06-10_20:00:58" # 210
            exp_5: "2025-06-10_20:01:09" # 210
            exp_6: "2025-06-10_20:01:14" # 210
            exp_7: "2025-06-10_20:01:23" # 210
            exp_8: "2025-06-10_20:01:29" # 210
            exp_9: "2025-06-10_20:01:37" # 210
            exp_10: "2025-06-10_20:01:45" # 210
        IAD:
            exp_1: "2025-06-18_00:11:26" # 210
            exp_2: "2025-06-18_00:11:28" # 210
            exp_3: "2025-06-18_00:11:39" # 210
            exp_4: "2025-06-18_00:11:50" # 210
            exp_5: "2025-06-18_00:12:02" # 210
            exp_6: "2025-06-18_00:12:15" # 210
            exp_7: "2025-06-18_00:12:21" # 210
            exp_8: "2025-06-18_00:12:36" # 210
            exp_9: "2025-06-14_15:45:22" # 210
            exp_10: "2025-06-14_14:08:44" # 210
        Refool:
            exp_1: "2025-06-15_19:37:27" # 210
            exp_2: "2025-06-15_19:37:09" # 210
            exp_3: "2025-06-15_17:14:02" # 210
            exp_4: "2025-06-15_17:13:18" # 210
            exp_5: "2025-06-15_19:26:56" # 210
            exp_6: "2025-06-15_19:26:20" # 210
            exp_7: "2025-06-15_19:31:39" # 210
            exp_8: "2025-06-15_19:34:41" # 210
            exp_9: "2025-06-15_19:02:04" # 210
            exp_10: "2025-06-15_17:13:19" # 210
        WaNet:
            exp_1: "2025-06-17_11:46:54" # 210
            exp_2: "2025-06-17_11:47:12" # 210
            exp_3: "2025-06-17_02:41:14" # 210
            exp_4: "2025-06-17_02:26:23" # 210
            exp_5: "2025-06-17_11:02:00" # 210
            exp_6: "2025-06-17_10:55:29" # 210
            exp_7: "2025-06-17_11:46:46" # 210
            exp_8: "2025-06-17_11:57:22" # 210
            exp_9: "2025-06-17_09:50:11" # 210
            exp_10: "2025-06-18_14:39:07" # 210
GTSRB:
    ResNet18:
        BadNets:
            exp_1: "2025-06-10_20:04:18" # 210
            exp_2: "2025-06-10_20:05:46" # 210
            exp_3: "2025-06-10_20:05:58" # 210
            exp_4: "2025-06-10_20:06:05" # 210
            exp_5: "2025-06-10_20:06:16" # 210
            exp_6: "2025-06-10_20:06:24" # 210
            exp_7: "2025-06-10_20:07:06" # 210
            exp_8: "2025-06-10_20:07:18" # 210
            exp_9: "2025-06-10_20:07:30" # 210
            exp_10: "2025-06-10_20:07:47" # 210
        IAD:
            exp_1: "2025-06-15_22:23:43" # 210
            exp_2: "2025-06-17_01:42:09"
            exp_3: "2025-06-11_21:05:59" # 210
            exp_4: "2025-06-11_21:05:55" # 210
            exp_5: "2025-06-11_21:06:43" # 210
            exp_6: "2025-06-11_21:06:28" # 210
            exp_7: "2025-06-11_21:07:02" # 210
            exp_8: "2025-06-11_21:07:08" # 210
            exp_9: "2025-06-11_21:07:14" # 210
            exp_10: "2025-06-11_21:07:09" # 210
        Refool:
            exp_1: "2025-06-17_04:22:15"
            exp_2: "2025-06-17_05:11:11"
            exp_3: "2025-06-15_22:23:42" # 210
            exp_4: "2025-06-15_22:23:50" # 210
            exp_5: "2025-06-15_22:25:04" # 210
            exp_6: "2025-06-15_22:26:07" # 210
            exp_7: "2025-06-15_22:26:16" # 210
            exp_8: "2025-06-15_22:26:26" # 210
            exp_9: "2025-06-15_22:26:38" # 210
            exp_10: "2025-06-15_22:26:46" # 210
        WaNet:
            exp_1: "2025-06-16_22:13:46" # 210
            exp_2: "2025-06-17_09:03:28"
            exp_3: "2025-06-16_21:10:55" # 210
            exp_4: "2025-06-16_21:34:25" # 210
            exp_5: "2025-06-16_21:06:56" # 210
            exp_6: "2025-06-16_21:48:42" # 210
            exp_7: "2025-06-16_21:40:13" # 210
            exp_8: "2025-06-16_21:48:11" # 210
            exp_9: "2025-06-16_21:21:15" # 210
            exp_10: "2025-06-16_21:38:12" # 210
    VGG19:
        BadNets:
            exp_1: "2025-06-18_12:45:06" # 210
            exp_2: "2025-06-18_12:45:13" # 210
            exp_3: "2025-06-16_21:58:48" # 210
            exp_4: "2025-06-16_21:58:56" # 210
            exp_5: "2025-06-16_21:59:06" # 210
            exp_6: "2025-06-16_21:59:09" # 210
            exp_7: "2025-06-16_21:59:25" # 210
            exp_8: "2025-06-16_21:59:35" # 210
            exp_9: "2025-06-16_21:59:46" # 210
            exp_10: "2025-06-16_21:59:55" # 210
        IAD:
            exp_1: "2025-06-11_21:19:06" # 210
            exp_2: "2025-06-11_21:18:40" # 210
            exp_3: "2025-06-11_21:19:11" # 210
            exp_4: "2025-06-11_21:18:44" # 210
            exp_5: "2025-06-11_21:18:33" # 210
            exp_6: "2025-06-11_21:18:41" # 210
            exp_7: "2025-06-11_21:20:29" # 210
            exp_8: "2025-06-11_21:18:54" # 210
            exp_9: "2025-06-11_21:17:59" # 210
            exp_10: "2025-06-11_21:20:40" # 210
        Refool:
            exp_1: "2025-06-17_02:35:27" # 210
            exp_2: "2025-06-17_02:35:24" # 210
            exp_3: "2025-06-17_03:55:15" # 210
            exp_4: "2025-06-17_03:55:24" # 210
            exp_5: "2025-06-26_17:37:46"
            exp_6: "2025-06-27_00:20:51"
            exp_7: "2025-06-17_02:33:42" # 210
            exp_8: "2025-06-17_02:34:52" # 210
            exp_9: "2025-06-17_02:30:52" # 210
            exp_10: "2025-06-17_02:37:24" # 210
        WaNet:
            exp_1: "2025-06-17_17:54:33" # 210
            exp_2: "2025-06-17_17:46:34" # 210
            exp_3: "2025-06-17_18:22:38" # 210
            exp_4: "2025-06-17_18:24:55" # 210
            exp_5: "2025-06-17_18:37:12" # 210
            exp_6: "2025-06-17_18:39:52" # 210
            exp_7: "2025-06-17_17:50:32" # 210
            exp_8: "2025-06-17_17:55:49" # 210
            exp_9: "2025-06-17_17:54:20" # 210
            exp_10: "2025-06-17_17:51:45" # 210
    DenseNet:
        BadNets:
            exp_1: "2025-06-18_20:42:48" # 210
            exp_2: "2025-06-18_20:42:59" # 210
            exp_3: "2025-06-17_13:13:31" # 210
            exp_4: "2025-06-17_12:32:26"
            exp_5: "2025-06-17_12:32:40"
            exp_6: "2025-06-17_20:07:44" # 210
            exp_7: "2025-06-17_20:07:54" # 210
            exp_8: "2025-06-18_14:51:56" # 210
            exp_9: "2025-06-17_20:09:16" # 210
            exp_10: "2025-06-17_21:27:06" # 210
        IAD:
            exp_1: "2025-06-19_13:54:33" # 210
            exp_2: "2025-06-18_12:47:16" # 210
            exp_3: "2025-06-18_12:47:15" # 210
            exp_4: "2025-06-18_12:47:17" # 210
            exp_5: "2025-06-18_12:47:21" # 210
            exp_6: "2025-06-19_13:05:04" # 210
            exp_7: "2025-06-20_12:36:50" # 210
            exp_8: "2025-06-19_00:13:33" # 210
            exp_9: "2025-06-18_21:36:19" # 210
            exp_10: "2025-06-18_12:47:58" # 210
        Refool:
            exp_1: "2025-06-19_13:03:15" # 210
            exp_2: "2025-06-19_13:03:58" # 210
            exp_3: "2025-06-18_07:37:27" # 210
            exp_4: "2025-06-18_08:57:29"
            exp_5: "2025-06-18_08:05:36"
            exp_6: "2025-06-18_13:15:16" # 210
            exp_7: "2025-06-18_13:15:17" # 210
            exp_8: "2025-06-19_12:16:23" # 210
            exp_9: "2025-06-18_06:32:20" # 210
            exp_10: "2025-06-18_14:45:10" # 210
        WaNet:
            exp_1: "2025-06-19_23:25:08" # 210
            exp_2: "2025-06-19_23:25:07" # 210
            exp_3: "2025-06-18_22:39:27" # 210
            exp_4: "2025-06-19_00:43:21"
            exp_5: "2025-06-18_16:47:29"
            exp_6: "2025-06-19_05:18:30" # 210
            exp_7: "2025-06-19_05:22:04" # 210
            exp_8: "2025-06-19_22:51:56" # 210
            exp_9: "2025-06-18_17:12:47" # 210
            exp_10: "2025-06-19_04:45:10" # 210
ImageNet2012_subset:
    ResNet18:
        BadNets:
            exp_1: "2025-06-13_23:24:58"
            exp_2: "2025-06-14_15:40:20"
            exp_3: "2025-06-14_15:41:28"
            exp_4: "2025-06-14_15:41:35"
            exp_5: "2025-06-18_23:28:06"
            exp_6: "2025-06-18_00:17:56"
            exp_7: "2025-06-20_13:07:21"
            exp_8: "2025-06-20_13:09:26"
            exp_9: "2025-06-20_17:41:28" # 210
            exp_10: "2025-06-20_18:03:25"
        IAD:
            exp_1: "2025-06-14_05:46:34"
            exp_2: "2025-06-15_20:30:58"
            exp_3: "2025-06-15_22:13:09"
            exp_4: "2025-06-18_23:32:28"
            exp_5: "2025-06-16_18:28:49"
            exp_6: "2025-06-18_14:53:14"
            exp_7: "2025-06-20_21:33:36"
            exp_8: "2025-06-20_21:54:36"
            exp_9: "2025-06-23_11:55:44"
            exp_10: "2025-06-21_06:53:46"
        Refool:
            exp_1: "2025-06-19_13:11:39"
            exp_2: "2025-06-16_15:46:49"
            exp_3: "2025-06-16_17:32:41"
            exp_4: "2025-06-15_17:16:21"
            exp_5: "2025-06-17_16:05:32"
            exp_6: "2025-06-19_14:33:12"
            exp_7: "2025-06-21_19:09:43"
            exp_8: "2025-06-21_18:02:01"
            exp_9: "2025-06-24_06:51:27"
            exp_10: "2025-06-22_04:07:27"
        WaNet:
            exp_1: "2025-06-20_01:59:29"
            exp_2: "2025-06-17_05:47:10"
            exp_3: "2025-06-17_08:13:47"
            exp_4: "2025-06-16_03:01:25"
            exp_5: "2025-06-18_06:18:12"
            exp_6: "2025-06-20_03:42:33"
            exp_7: "2025-06-22_07:30:49"
            exp_8: "2025-06-22_05:44:21"
            exp_9: "2025-06-24_18:33:02"
            exp_10: "2025-06-22_14:59:17"
    DenseNet:
        BadNets:
            exp_1: "2025-06-23_11:21:55"
            exp_2: "2025-06-23_11:51:59"
            exp_3: "2025-06-23_13:01:14"
            exp_4: "2025-07-01_11:42:12"
            exp_5: "2025-07-03_12:14:13"
            exp_6: "2025-06-26_13:20:48"
            exp_7: "2025-06-27_17:57:55"
            exp_8: "2025-06-27_17:57:55"
            exp_9: "2025-06-27_18:02:05"
            exp_10: "2025-06-05_20:51:56"
        IAD:
            exp_1: "2025-06-24_06:00:16"
            exp_2: "2025-06-24_11:16:18"
            exp_3: "2025-06-26_03:56:35"
            exp_4: "2025-06-23_14:24:44"
            exp_5: "2025-07-04_02:56:59"
            exp_6: "2025-06-27_16:55:57"
            exp_7: "2025-06-28_14:14:47"
            exp_8: "2025-06-28_19:31:55"
            exp_9: "2025-06-29_08:17:37"
            exp_10: "2025-07-01_11:38:44"
        Refool:
            exp_1: "2025-06-25_09:20:57"
            exp_2: "2025-06-25_13:16:42"
            exp_3: "2025-06-27_04:36:20"
            exp_4: "2025-06-25_07:36:54"
            exp_5: "2025-07-05_05:12:28"
            exp_6: "2025-06-29_00:57:18"
            exp_7: "2025-06-29_12:08:45"
            exp_8: "2025-06-30_03:33:00"
            exp_9: "2025-06-30_05:04:43"
            exp_10: "2025-07-03_02:28:26"
        WaNet:
            exp_1: "2025-06-26_08:01:38"
            exp_2: "2025-06-26_13:36:30"
            exp_3: "2025-06-28_00:00:43"
            exp_4: "2025-06-26_05:47:20"
            exp_5: "2025-07-06_08:01:29"
            exp_6: "2025-06-30_02:42:06"
            exp_7: "2025-06-30_05:15:07"
            exp_8: "2025-07-01_07:22:14"
            exp_9: "2025-06-30_20:15:50"
            exp_10: "2025-07-03_18:57:56"