CIFAR10:
    ResNet18:
        BadNets:
            exp_1: "2025-06-04_18:18:26"
            exp_2: "2025-06-05_14:22:41"
            exp_3: "2025-06-06_11:41:25"
            exp_4: "2025-06-07_09:23:55"
            exp_5: "2025-06-08_13:37:34"
            exp_6: "2025-06-08_23:13:31"
            exp_7: "2025-06-09_01:09:15"
            exp_8: "2025-06-09_01:09:15"
            exp_9: "2025-06-09_05:00:28"
            exp_10: "2025-06-06_18:37:18"
        IAD:
            exp_1: "2025-06-04_18:24:50"
            exp_2: "2025-06-05_14:33:30"
            exp_3: "2025-06-06_11:53:22"
            exp_4: "2025-06-07_09:35:48"
            exp_5: "2025-06-08_13:44:03"
            exp_6: "2025-06-08_23:20:35"
            exp_7: "2025-06-09_01:17:21"
            exp_8: "2025-06-09_03:35:33"
            exp_9: "2025-06-09_05:07:16"
            exp_10: "2025-06-06_18:54:02"
        Refool:
            exp_1: "2025-06-04_18:31:56"
            exp_2: "2025-06-05_14:45:20"
            exp_3: "2025-06-06_12:06:11"
            exp_4: "2025-06-07_09:49:29"
            exp_5: "2025-06-08_13:52:13"
            exp_6: "2025-06-08_23:28:56"
            exp_7: "2025-06-09_01:26:34"
            exp_8: "2025-06-09_03:43:57"
            exp_9: "2025-06-09_05:15:38"
            exp_10: "2025-06-06_19:11:49"
        WaNet:
            exp_1: "2025-06-04_19:04:03"
            exp_2: "2025-06-05_14:56:59"
            exp_3: "2025-06-06_12:18:49"
            exp_4: "2025-06-07_10:01:32"
            exp_5: "2025-06-08_14:02:43"
            exp_6: "2025-06-08_23:36:24"
            exp_7: "2025-06-09_01:36:52"
            exp_8: "2025-06-09_03:52:03"
            exp_9: "2025-06-09_05:22:16"
            exp_10: "2025-06-06_19:27:50"
    VGG19:
        BadNets:
            exp_1: "2025-06-04_19:09:53"
            exp_2: "2025-06-05_15:07:25"
            exp_3: "2025-06-06_12:29:13"
            exp_4: "2025-06-07_10:11:13"
            exp_5: "2025-06-08_14:13:41"
            exp_6: "2025-06-08_23:42:29"
            exp_7: "2025-06-09_01:44:12"
            exp_8: "2025-06-09_03:59:20"
            exp_9: "2025-06-09_05:26:46"
            exp_10: "2025-06-06_17:31:35"
        IAD:
            exp_1: "2025-06-04_19:17:41"
            exp_2: "2025-06-05_15:19:10"
            exp_3: "2025-06-06_12:41:49"
            exp_4: "2025-06-07_10:23:50"
            exp_5: "2025-06-08_14:26:14"
            exp_6: "2025-06-08_23:50:16"
            exp_7: "2025-06-09_01:53:41"
            exp_8: "2025-06-09_04:08:13"
            exp_9: "2025-06-09_05:33:38"
            exp_10: "2025-06-06_17:48:29"
        Refool:
            exp_1: "2025-06-04_19:26:03"
            exp_2: "2025-06-05_15:31:34"
            exp_3: "2025-06-06_12:55:00"
            exp_4: "2025-06-07_10:37:49"
            exp_5: "2025-06-08_22:15:17"
            exp_6: "2025-06-08_23:59:12"
            exp_7: "2025-06-09_02:04:05"
            exp_8: "2025-06-09_04:16:19"
            exp_9: "2025-06-09_05:41:37"
            exp_10: "2025-06-06_18:06:26"
        WaNet:
            exp_1: "2025-06-04_19:34:13"
            exp_2: "2025-06-05_15:59:03"
            exp_3: "2025-06-06_13:29:43"
            exp_4: "2025-06-07_10:50:27"
            exp_5: "2025-06-08_22:28:03"
            exp_6: "2025-06-09_00:08:02"
            exp_7: "2025-06-09_02:19:02"
            exp_8: "2025-06-09_04:26:15"
            exp_9: "2025-06-09_06:05:35"
            exp_10: "2025-06-06_18:22:47"
    DenseNet:
        BadNets:
            exp_1: "2025-06-04_19:42:53"
            exp_2: "2025-06-05_16:10:12"
            exp_3: "2025-06-06_13:41:27"
            exp_4: "2025-06-07_11:02:29"
            exp_5: "2025-06-08_22:34:13"
            exp_6: "2025-06-09_00:15:52"
            exp_7: "2025-06-09_02:29:38"
            exp_8: "2025-06-09_04:30:54"
            exp_9: "2025-06-09_06:10:55"
            exp_10: "2025-06-06_16:20:09"
        IAD:
            exp_1: "2025-06-04_19:53:59"
            exp_2: "2025-06-05_16:25:40"
            exp_3: "2025-06-06_13:54:53"
            exp_4: "2025-06-07_11:16:00"
            exp_5: "2025-06-08_22:43:18"
            exp_6: "2025-06-09_00:28:26"
            exp_7: "2025-06-09_02:43:25"
            exp_8: "2025-06-09_04:38:00"
            exp_9: "2025-06-09_06:19:01"
            exp_10: "2025-06-06_16:37:44"
        Refool:
            exp_1: "2025-06-04_20:06:13"
            exp_2: "2025-06-05_16:41:36"
            exp_3: "2025-06-06_14:09:19"
            exp_4: "2025-06-07_11:29:28"
            exp_5: "2025-06-08_22:53:26"
            exp_6: "2025-06-09_00:41:44"
            exp_7: "2025-06-09_02:57:18"
            exp_8: "2025-06-09_04:46:18"
            exp_9: "2025-06-09_06:28:09"
            exp_10: "2025-06-06_16:56:25"
        WaNet:
            exp_1: "2025-06-04_20:30:56"
            exp_2: "2025-06-05_16:57:14"
            exp_3: "2025-06-06_14:24:42"
            exp_4: "2025-06-07_11:51:28"
            exp_5: "2025-06-08_23:03:35"
            exp_6: "2025-06-09_00:55:47"
            exp_7: "2025-06-09_03:15:03"
            exp_8: "2025-06-09_04:53:49"
            exp_9: "2025-06-09_06:50:08"
            exp_10: "2025-06-06_17:14:27"
GTSRB:
    ResNet18:
        BadNets:
            exp_1: "2025-06-04_20:41:29"
            exp_2: "2025-06-05_17:11:59"
            exp_3: "2025-06-06_14:39:23"
            exp_4: "2025-06-07_12:03:14"
            exp_5: "2025-06-08_13:52:14"
            exp_6: "2025-06-08_22:31:57"
            exp_7: "2025-06-08_23:32:57"
            exp_8: "2025-06-09_00:28:12"
            exp_9: "2025-06-09_01:26:27"
            exp_10: "2025-06-06_15:15:33"
        IAD:
            exp_1: "2025-06-04_20:47:31"
            exp_2: "2025-06-05_17:21:50"
            exp_3: "2025-06-06_14:50:39"
            exp_4: "2025-06-07_12:14:03"
            exp_5: "2025-06-08_13:59:57"
            exp_6: "2025-06-08_22:37:42"
            exp_7: "2025-06-08_23:38:52"
            exp_8: "2025-06-09_00:34:26"
            exp_9: "2025-06-09_01:32:41"
            exp_10: "2025-06-06_15:31:06"
        Refool:
            exp_1: "2025-06-04_20:54:16"
            exp_2: "2025-06-05_17:32:27"
            exp_3: "2025-06-06_15:02:31"
            exp_4: "2025-06-07_12:25:18"
            exp_5: "2025-06-08_14:09:52"
            exp_6: "2025-06-08_22:44:10"
            exp_7: "2025-06-08_23:45:39"
            exp_8: "2025-06-09_00:41:31"
            exp_9: "2025-06-09_01:39:47"
            exp_10: "2025-06-06_15:47:32"
        WaNet:
            exp_1: "2025-06-04_21:00:50"
            exp_2: "2025-06-05_17:42:52"
            exp_3: "2025-06-06_15:14:18"
            exp_4: "2025-06-07_12:36:38"
            exp_5: "2025-06-08_14:19:31"
            exp_6: "2025-06-08_22:50:19"
            exp_7: "2025-06-08_23:52:19"
            exp_8: "2025-06-09_00:48:36"
            exp_9: "2025-06-09_01:47:16"
            exp_10: "2025-06-06_16:03:54"
    VGG19:
        BadNets:
            exp_1: "2025-06-04_21:07:36"
            exp_2: "2025-06-05_17:53:05"
            exp_3: "2025-06-06_15:26:11"
            exp_4: "2025-06-07_12:48:00"
            exp_5: "2025-06-08_14:28:25"
            exp_6: "2025-06-08_22:56:28"
            exp_7: "2025-06-08_23:58:35"
            exp_8: "2025-06-09_00:55:17"
            exp_9: "2025-06-09_01:54:05"
            exp_10: "2025-06-06_14:08:19"
        IAD:
            exp_1: "2025-06-04_21:15:58"
            exp_2: "2025-06-05_18:03:24"
            exp_3: "2025-06-06_15:37:19"
            exp_4: "2025-06-07_12:59:01"
            exp_5: "2025-06-08_14:39:07"
            exp_6: "2025-06-08_23:02:53"
            exp_7: "2025-06-09_00:05:16"
            exp_8: "2025-06-09_01:02:44"
            exp_9: "2025-06-09_02:01:46"
            exp_10: "2025-06-06_14:24:45"
        Refool:
            exp_1: "2025-06-04_21:24:49"
            exp_2: "2025-06-05_18:14:15"
            exp_3: "2025-06-06_15:49:04"
            exp_4: "2025-06-09_15:36:14"
            exp_5: "2025-06-08_22:12:23"
            exp_6: "2025-06-08_23:09:57"
            exp_7: "2025-06-09_00:12:45"
            exp_8: "2025-06-09_01:10:44"
            exp_9: "2025-06-09_02:09:22"
            exp_10: "2025-06-06_14:41:40"
        WaNet:
            exp_1: "2025-06-04_21:33:51"
            exp_2: "2025-06-05_18:25:07"
            exp_3: "2025-06-06_16:01:46"
            exp_4: "2025-06-09_15:30:21"
            exp_5: "2025-06-08_22:25:47"
            exp_6: "2025-06-08_23:26:26"
            exp_7: "2025-06-09_00:20:40"
            exp_8: "2025-06-09_01:18:50"
            exp_9: "2025-06-09_02:23:19"
            exp_10: "2025-06-06_14:59:03"
    DenseNet:
        BadNets:
            exp_1: "2025-06-04_21:42:13"
            exp_2: "2025-06-05_18:35:47"
            exp_3: "2025-06-06_16:13:24"
            exp_4: "2025-06-08_13:53:09"
            exp_5: "2025-06-08_22:19:52"
            exp_6: "2025-06-08_23:03:49"
            exp_7: "2025-06-08_23:52:17"
            exp_8: "2025-06-09_00:43:17"
            exp_9: "2025-06-07_11:52:29"
            exp_10: "2025-06-06_12:47:18"
        IAD:
            exp_1: "2025-06-04_22:07:17"
            exp_2: "2025-06-05_18:58:27"
            exp_3: "2025-06-06_16:32:40"
            exp_4: "2025-06-08_14:22:13"
            exp_5: "2025-06-08_22:30:42"
            exp_6: "2025-06-08_23:15:12"
            exp_7: "2025-06-09_00:04:32"
            exp_8: "2025-06-09_00:56:33"
            exp_9: "2025-06-07_12:12:23"
            exp_10: "2025-06-06_13:07:02"
        Refool:
            exp_1: "2025-06-04_22:33:16"
            exp_2: "2025-06-05_19:21:50"
            exp_3: "2025-06-06_16:52:29"
            exp_4: "2025-06-08_21:57:06"
            exp_5: "2025-06-08_22:42:20"
            exp_6: "2025-06-08_23:27:19"
            exp_7: "2025-06-09_00:17:07"
            exp_8: "2025-06-09_01:10:56"
            exp_9: "2025-06-07_12:33:07"
            exp_10: "2025-06-06_13:27:43"
        WaNet:
            exp_1: "2025-06-04_22:58:49"
            exp_2: "2025-06-05_19:44:49"
            exp_3: "2025-06-06_17:12:22"
            exp_4: "2025-06-08_22:08:56"
            exp_5: "2025-06-08_22:53:25"
            exp_6: "2025-06-08_23:40:27"
            exp_7: "2025-06-09_00:30:16"
            exp_8: "2025-06-09_01:25:33"
            exp_9: "2025-06-09_15:36:45"
            exp_10: "2025-06-06_13:48:11"
ImageNet2012_subset:
    ResNet18:
        BadNets:
            exp_1: "2025-06-04_23:24:00"
            exp_2: "2025-06-05_20:06:58"
            exp_3: "2025-06-06_17:31:54"
            exp_4: "2025-06-08_21:37:09"
            exp_5: "2025-06-09_13:21:30"
            exp_6: "2025-06-10_12:06:56"
            exp_7: "2025-06-09_15:41:50"
            exp_8: "2025-06-10_12:18:20"
            exp_9: "2025-06-07_05:28:14"
            exp_10: "2025-06-06_06:15:27"
        IAD:
            exp_1: "2025-06-05_00:33:41"
            exp_2: "2025-06-05_21:16:21"
            exp_3: "2025-06-06_18:44:04"
            exp_4: "2025-06-08_22:48:11"
            exp_5: "2025-06-09_17:18:55"
            exp_6: "2025-06-10_13:38:31"
            exp_7: "2025-06-09_17:16:44"
            exp_8: "2025-06-10_13:54:24"
            exp_9: "2025-06-07_06:45:23"
            exp_10: "2025-06-06_07:34:21"
        Refool:
            exp_1: "2025-06-05_01:56:53"
            exp_2: "2025-06-05_22:38:40"
            exp_3: "2025-06-06_20:07:34"
            exp_4: "2025-06-09_00:12:45"
            exp_5: "2025-06-09_18:58:08"
            exp_6: "2025-06-10_15:38:19"
            exp_7: "2025-06-09_18:50:04"
            exp_8: "2025-06-10_15:51:39"
            exp_9: "2025-06-07_08:14:19"
            exp_10: "2025-06-06_09:02:15"
        WaNet:
            exp_1: "2025-06-05_03:09:51"
            exp_2: "2025-06-05_23:59:38"
            exp_3: "2025-06-06_21:28:08"
            exp_4: "2025-06-09_01:31:50"
            exp_5: "2025-06-09_20:45:54"
            exp_6: "2025-06-10_18:16:21"
            exp_7: "2025-06-09_20:41:08"
            exp_8: "2025-06-10_18:20:23"
            exp_9: "2025-06-07_09:34:43"
            exp_10: "2025-06-06_10:27:52"
    DenseNet:
        BadNets:
            exp_1: "2025-06-05_05:22:04"
            exp_2: "2025-06-06_02:19:35"
            exp_3: "2025-06-06_23:56:42"
            exp_4: "2025-06-09_03:48:20"
            exp_5: "2025-06-10_03:26:20"
            exp_6: "2025-06-10_12:19:32"
            exp_7: "2025-06-10_12:20:40"
            exp_8: "2025-06-10_12:21:24"
            exp_9: "2025-06-06_19:42:03"
            exp_10: "2025-06-05_20:53:43"
        IAD:
            exp_1: "2025-06-05_06:31:05"
            exp_2: "2025-06-06_03:35:12"
            exp_3: "2025-06-07_01:18:56"
            exp_4: "2025-06-09_05:00:02"
            exp_5: "2025-06-10_12:32:17"
            exp_6: "2025-06-10_14:05:37"
            exp_7: "2025-06-10_14:41:51"
            exp_8: "2025-06-10_14:42:01"
            exp_9: "2025-06-06_21:00:32"
            exp_10: "2025-06-05_22:01:30"
        Refool:
            exp_1: "2025-06-05_10:47:47"
            exp_2: "2025-06-06_08:06:27"
            exp_3: "2025-06-07_05:47:16"
            exp_4: "2025-06-09_09:22:51"
            exp_5: "2025-06-10_18:22:20"
            exp_6: "2025-06-10_19:53:21"
            exp_7: "2025-06-10_21:51:47"
            exp_8: "2025-06-10_21:58:08"
            exp_9: "2025-06-07_01:37:03"
            exp_10: "2025-06-06_02:26:17"
        WaNet:
            exp_1: "2025-06-05_12:03:09"
            exp_2: "2025-06-06_09:25:37"
            exp_3: "2025-06-07_07:09:38"
            exp_4: "2025-06-09_10:46:46"
            exp_5: "2025-06-10_21:16:27"
            exp_6: "2025-06-10_21:55:27"
            exp_7: "2025-06-10_23:28:03"
            exp_8: "2025-06-10_23:38:17"
            exp_9: "2025-06-07_03:05:09"
            exp_10: "2025-06-06_03:49:56"